version: '3.8'

services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
      - ./configs:/app/configs
      - ./models:/app/models
      - ./scripts:/app/scripts
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/camel_extensions
      - REDIS_URL=redis://redis:6379/0
      - API_PORT=8000
      - DEBUG=true
    depends_on:
      - db
      - redis
    restart: unless-stopped

  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=camel_extensions
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  ui:
    image: streamlit/streamlit:latest
    ports:
      - "8501:8501"
    volumes:
      - ./gui:/app/gui
    command: streamlit run gui/app.py
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_HEADLESS=true
      - API_URL=http://api:8000
    depends_on:
      - api
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data: